services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock:/run/sock
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - rinha

  api1:
    image: rinha-2026:local
    cpuset: "0"
    environment:
      INDEX_PATH: /app/resources/index.bin
      MCC_RISK_PATH: /app/resources/mcc_risk.json
      SOCKET_PATH: /run/sock/api1.sock
    volumes:
      - sock:/run/sock
    ulimits:
      nofile: 65535
    healthcheck:
      test: ["CMD", "curl", "-sf", "--unix-socket", "/run/sock/api1.sock", "http://localhost/ready"]
      interval: 3s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "155MB"
    networks:
      - rinha

  api2:
    image: rinha-2026:local
    cpuset: "2"
    environment:
      INDEX_PATH: /app/resources/index.bin
      MCC_RISK_PATH: /app/resources/mcc_risk.json
      SOCKET_PATH: /run/sock/api2.sock
    volumes:
      - sock:/run/sock
    ulimits:
      nofile: 65535
    healthcheck:
      test: ["CMD", "curl", "-sf", "--unix-socket", "/run/sock/api2.sock", "http://localhost/ready"]
      interval: 3s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "155MB"
    networks:
      - rinha

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  rinha:
    driver: bridge
