x-api: &api
  image: ghcr.io/joseiedo/rinha-de-backend-2026:v0.0.16
  pull_policy: always
  volumes:
    - sockets:/sockets
  deploy:
    resources:
      limits:
        cpus: "0.40"
        memory: "160MB"

services:
  api1:
    <<: *api
    environment:
      INDEX_PATH: /app/resources/index.bin
      SOCKET_PATH: /sockets/api1.sock

  api2:
    <<: *api
    environment:
      INDEX_PATH: /app/resources/index.bin
      SOCKET_PATH: /sockets/api2.sock

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
