x-api: &api
  image: ghcr.io/joseiedo/rinha-de-backend-2026:v0.0.13
  pull_policy: always
  volumes:
    - sockets:/sockets
  deploy:
    resources:
      limits:
        cpus: "0.30"
        memory: "150MB"

services:
  api1:
    <<: *api
    cpuset: "0,1"
    environment:
      INDEX_PATH: /app/resources/index.bin
      SOCKET_PATH: /sockets/api1.sock

  api2:
    <<: *api
    cpuset: "2,3"
    environment:
      INDEX_PATH: /app/resources/index.bin
      SOCKET_PATH: /sockets/api2.sock

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "46MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
